### ISSUE TITLE
Don't assume that ID cannot be set if the record cannot be found

### ISSUE THREAD

**Issue by carlthuringer** [jsonapi-suite/nested_attribute_reassignable#1]
We use UUIDs on our models, so we have no problem with callers specifying the UUID on nested relationships when they hit the create endpoint.

# Behavior
However, the module assumes that if an ID is present, then it should find an existing object for the relationship. When no object is found, it raises an error.

# Expected
Instead, it should be possible to either specify as an option that id is assignable to a new record, or simply update the code to attempt creation anyways.

What do you think?

**Comment by carlthuringer** [comment]
Thinking some more about this, I believe that I'm pushing a bit too far in saying that one should be able to create a relationship when making a `put/patch` request. This works as expected during `POST` requests.

**Comment by richmolj** [comment]
@carlthuringer I've actually used models with a `uuid` column without issues. I'm not totally sure I understand the issue though...maybe you could show the full request / models? You *should* be able to create a relationship in a `PUT`, and you should be able to use `uuid` instead of `id`.

Also, be aware of the `:lookup_key` option:

```ruby
class Post < ApplicationRecord
  reassignable_nested_attributes_for :tags, lookup_key: uuid
end

post = Post.first
tag = Tag.first
@post.update_attributes(tags_attributes: [{ id: tag.uuid }])
@post.reload.tags # => [tag]
```

**Comment by carlthuringer** [comment]
Thanks, @richmolj , in this case my uuid is actually in the `id` column, but it's good to know about the lookup_key to apply this to legacy projects where that isn't the case.

To clarify with your example:
```ruby
class Post < ApplicationRecord
  reassignable_nested_attributes_for :tags, lookup_key: uuid
end

post = Post.first
# tag = Tag.first # Tag doesn't exist!
# Instead, trying to create a new tag by updating...
@post.update_attributes(tags_attributes: [{ id: tag.uuid, title: "Articles" }])
# > Results in RecordNotFound error.
```

As I said, I think it may actually be a violation of user expectations, that `POST` creates resources, and `PUT` updates them. If this worked the way I mistakenly thought it should, then there would be potential for *surprising effects* like creating a new tag with an empty title where you intended to use an existing one, but truncated/typoed the id.

**Comment by richmolj** [comment]
So in other words

* you can update the post and create a new tag during that update
* you can update the post and associate an existing tag during that update

But you **cannot** create a new tag *with a particular id*. Is that correct?
